apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ds7g
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-ds7g@sha256:63836b524a1a0d7ffade4c3d7ad4adc1e7f96a4acd88e838509869fd8b4258ad
        name: my-nodejs
        resources: {}
status: {}
